language: node_js

node_js:
  - "7"
before_install:
  - "curl -L https://raw.githubusercontent.com/arunoda/travis-ci-meteor-packages/master/configure.sh | /bin/sh"
before_script:
  - "npm install -g coffee-script"
  - "npm install -g spacejam"
  - "export PATH=$HOME/.meteor:$PATH"

script: "spacejam test-packages ./"
