version: 2
jobs:
  test:
    docker:
      - image: circleci/node:11.11.0
    steps:
      - checkout
      - run: curl https://install.meteor.com | /bin/sh
      - run: npm install
      - run: npm run test
