version: 2
jobs:
  build:
    docker:
      - image: circleci/node:15.14.0
    steps:
      - checkout
      - run: curl https://install.meteor.com | /bin/sh
      - run: npm install
      - run: npm run test
