name: "tests"
on: ["push", "pull_request"]
jobs:
  tests:
    name: npm test
    runs-on: node:17.2.0-stretch
    steps:
    - name: Install Meteor
      run: curl https://install.meteor.com | /bin/sh
    - name: npm install
      run: npm install
    - name: npm test
      run: npm test

  bundle:
    name: npm run bundle
    runs-on: node:17.2.0-stretch
    steps:
    - name: Install Meteor
      run: curl https://install.meteor.com | /bin/sh
    - name: npm install
      run: npm install
    - name: npm test
      run: npm run bundle
